#!/usr/bin/env bash

tree-sitter highlight --scope source.cog -H /dev/stdin | sed -z '
  s/.*<table>\n\(.*\)\n<\/table>.*/\1/
  s/<tr><td class=line-number>[0-9]\+<\/td><td class=line>\([^\n]*\)\n<\/td><\/tr>/\1/g'
